In [2]:
from tensorflow.keras.applications.mobilenet import MobileNet
from keras.optimizers import Adam
from keras.layers import *
from keras.models import Model

In [4]:
model = MobileNet(input_shape=(224,224,3),weights="imagenet",include_top=False)

17225924/17225924 [==============================] - 56s 3us/step


In [7]:
model.summary()
model.input
model.output

Model: "mobilenet_1.00_224"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 conv1 (Conv2D)              (None, 112, 112, 32)      864       
                                                                 
 conv1_bn (BatchNormalizatio  (None, 112, 112, 32)     128       
 n)                                                              
                                                                 
 conv1_relu (ReLU)           (None, 112, 112, 32)      0         
                                                                 
 conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)     288       
                                                                 
 conv_dw_1_bn (BatchNormaliz  (None, 112, 112, 32)     128       
 ation)                                         

<KerasTensor: shape=(None, 7, 7, 1024) dtype=float32 (created by layer 'conv_pw_13_relu')>

In [8]:
av1 = GlobalAveragePooling2D()(model.output)
fc1 = Dense(256,activation="relu")(av1)
d1 = Dropout(0.5)(fc1)
fc2 = Dense(10,activation="softmax")(d1)

new_model = Model(model.input,fc2)

In [10]:
new_model.summary()
new_model.output

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 conv1 (Conv2D)              (None, 112, 112, 32)      864       
                                                                 
 conv1_bn (BatchNormalizatio  (None, 112, 112, 32)     128       
 n)                                                              
                                                                 
 conv1_relu (ReLU)           (None, 112, 112, 32)      0         
                                                                 
 conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)     288       
                                                                 
 conv_dw_1_bn (BatchNormaliz  (None, 112, 112, 32)     128       
 ation)                                                      

<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'dense_1')>

In [13]:
adam = Adam(learning_rate=0.00003)
# new_model.compile(loss="categorical_crossentropy",optimizer=adam,metrics=["accuracy"])

In [14]:
for ix in range(len(new_model.layers)):
    print(ix,new_model.layers[ix])

0 <keras.engine.input_layer.InputLayer object at 0x00000260104AE200>
1 <keras.layers.convolutional.conv2d.Conv2D object at 0x0000026012E072E0>
2 <keras.layers.normalization.batch_normalization.BatchNormalization object at 0x0000026059BFBAC0>
3 <keras.layers.activation.relu.ReLU object at 0x0000026012E07820>
4 <keras.layers.convolutional.depthwise_conv2d.DepthwiseConv2D object at 0x0000026012E30160>
5 <keras.layers.normalization.batch_normalization.BatchNormalization object at 0x0000026012E31FC0>
6 <keras.layers.activation.relu.ReLU object at 0x0000026012E322C0>
7 <keras.layers.convolutional.conv2d.Conv2D object at 0x0000026012E32B00>
8 <keras.layers.normalization.batch_normalization.BatchNormalization object at 0x0000026012E320E0>
9 <keras.layers.activation.relu.ReLU object at 0x0000026012E33B50>
10 <keras.layers.reshaping.zero_padding2d.ZeroPadding2D object at 0x0000026012E33280>
11 <keras.layers.convolutional.depthwise_conv2d.DepthwiseConv2D object at 0x0000026012E39E70>
12 <keras.la

In [25]:
for ix in range(80):
    new_model.layers[ix].trainable = False
new_model.compile(loss="categorical_crossentropy",optimizer=adam,metrics=["accuracy"])

In [26]:
new_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 conv1 (Conv2D)              (None, 112, 112, 32)      864       
                                                                 
 conv1_bn (BatchNormalizatio  (None, 112, 112, 32)     128       
 n)                                                              
                                                                 
 conv1_relu (ReLU)           (None, 112, 112, 32)      0         
                                                                 
 conv_dw_1 (DepthwiseConv2D)  (None, 112, 112, 32)     288       
                                                                 
 conv_dw_1_bn (BatchNormaliz  (None, 112, 112, 32)     128       
 ation)                                                      

In [27]:
# Now dataset import

In [28]:
from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(rescale=1.0/255)
train_generator = datagen.flow_from_directory("D:\Aiml\Data Science CB\\67\\train",target_size=(224,224),batch_size=32)

Found 1642 images belonging to 10 classes.


In [29]:
train_generator.class_indices

{'Aerodactyl': 0,
 'Bulbasaur': 1,
 'Charmander': 2,
 'Dratini': 3,
 'Fearow': 4,
 'Meowth': 5,
 'Pikachu': 6,
 'Psyduck': 7,
 'Spearow': 8,
 'Squirtle': 9}

In [31]:
hist = new_model.fit(train_generator,epochs=10,steps_per_epoch=45)

Epoch 1/10
16/45 [=========>....................] - ETA: 30s - loss: 3.3212 - accuracy: 0.0859

d:\Python\lib\site-packages\PIL\Image.py:979: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


45/45 [==============================] - 50s 1s/step - loss: 3.0241 - accuracy: 0.1187
Epoch 2/10
45/45 [==============================] - 34s 751ms/step - loss: 2.4659 - accuracy: 0.1925
Epoch 3/10
45/45 [==============================] - 32s 701ms/step - loss: 2.2084 - accuracy: 0.2595
Epoch 4/10
45/45 [==============================] - 32s 700ms/step - loss: 1.9857 - accuracy: 0.3159
Epoch 5/10
45/45 [==============================] - 32s 703ms/step - loss: 1.7614 - accuracy: 0.3963
Epoch 6/10
45/45 [==============================] - 33s 728ms/step - loss: 1.6134 - accuracy: 0.4633
Epoch 7/10
45/45 [==============================] - 34s 747ms/step - loss: 1.4699 - accuracy: 0.5229
Epoch 8/10
45/45 [==============================] - 33s 718ms/step - loss: 1.3983 - accuracy: 0.5529
Epoch 9/10
45/45 [==============================] - 34s 752ms/step - loss: 1.3204 - accuracy: 0.5663
Epoch 10/10
45/45 [==============================] - 32s 719ms/step - loss: 1.2677 - accuracy: 0.5846


In [65]:
y_test = []
new_model.output

<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'dense_1')>

In [66]:
from keras.utils import load_img,img_to_array
import os
import numpy as np
for i in os.listdir("D:\Aiml\Data Science CB\\67\images"):
    img = load_img("D:\Aiml\Data Science CB\\67\images\\"+i,target_size=(224,224))
    img = img_to_array(img)/255.0
    img = np.expand_dims(img,axis=0)
    p = new_model.predict(img)
    y_test.append(np.argmax(p,axis=-1))

1/1 [==============================] - 0s 61ms/step


In [99]:
y_test[0][2]

[array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([9], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([7], dtype=int64),
 array([6], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([1], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([6], dtype=int64),
 array([1], dtype=int64),
 array([7], dtype=int64),
 array([7], dtype=int64),
 array([7], 

In [101]:
import pandas as pd
cnt = 0
output = []
for i in os.listdir("D:\Aiml\Data Science CB\\67\images"):
    output.append([i,y_test[cnt][0]])
    cnt += 1
output

[['test_0.jpg', 0],
 ['test_1.jpg', 0],
 ['test_10.jpg', 1],
 ['test_100.jpg', 6],
 ['test_101.jpg', 6],
 ['test_102.jpg', 6],
 ['test_103.jpg', 6],
 ['test_104.jpg', 6],
 ['test_105.jpg', 9],
 ['test_106.jpg', 6],
 ['test_107.jpg', 6],
 ['test_108.jpg', 7],
 ['test_109.jpg', 6],
 ['test_11.jpg', 1],
 ['test_110.jpg', 1],
 ['test_111.jpg', 6],
 ['test_112.jpg', 6],
 ['test_113.jpg', 6],
 ['test_114.jpg', 6],
 ['test_115.jpg', 6],
 ['test_116.jpg', 6],
 ['test_117.jpg', 6],
 ['test_118.jpg', 6],
 ['test_119.jpg', 6],
 ['test_12.jpg', 1],
 ['test_120.jpg', 6],
 ['test_121.jpg', 6],
 ['test_122.jpg', 6],
 ['test_123.jpg', 6],
 ['test_124.jpg', 6],
 ['test_125.jpg', 6],
 ['test_126.jpg', 6],
 ['test_127.jpg', 6],
 ['test_128.jpg', 6],
 ['test_129.jpg', 6],
 ['test_13.jpg', 1],
 ['test_130.jpg', 7],
 ['test_131.jpg', 7],
 ['test_132.jpg', 7],
 ['test_133.jpg', 7],
 ['test_134.jpg', 7],
 ['test_135.jpg', 1],
 ['test_136.jpg', 1],
 ['test_137.jpg', 7],
 ['test_138.jpg', 1],
 ['test_139.jpg', 

In [102]:
out = pd.DataFrame(output,columns=["Name","Class"])
print(out)
out.to_csv("submission.csv",index=False)

             Name  Class
0      test_0.jpg      0
1      test_1.jpg      0
2     test_10.jpg      1
3    test_100.jpg      6
4    test_101.jpg      6
..            ...    ...
182   test_95.jpg      9
183   test_96.jpg      5
184   test_97.jpg      9
185   test_98.jpg      6
186   test_99.jpg      1

[187 rows x 2 columns]
